version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_9
    ports:
      - "8080:80"
    volumes:
      - /home/comneta5/kelompok9/pkl-center/:/var/www/html
      - /home/comneta5/kelompok9/pkl-center/nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app_network

  php:
    image: php:8.1-fpm
    container_name: php_9
    volumes:
      - /home/comneta5/kelompok9/pkl-center/:/var/www/html
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql && php-fpm"
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: mysql_9
    environment:
      MYSQL_ROOT_PASSWORD: GantiPasswordKuat123!
      MYSQL_DATABASE: pkl_center
      MYSQL_USER: admin
      MYSQL_PASSWORD: AdminPkl@2026!
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_9
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: GantiPasswordKuat123!
    depends_on:
      - mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network: